class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'up'
        self.UnzipMirrorCommand = 'unzip'
        self.TarMirrorCommand = 'tar'
        self.CancelMirror = 'stop'
        self.CancelAllCommand = 'stopall'
        self.ListCommand = 'find'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart2'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help2'
        self.LogCommand = 'log2'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'drive'
        self.CountCommand = 'count2'
        self.WatchCommand = 'ytdl'
        self.TarWatchCommand = 'tarytdl'
        self.DeleteCommand = 'delete'
        self.UsageCommand = 'usage'
        self.MediaInfoCommand = 'mediainfo2'
        self.ConfigMenuCommand = 'config2'
        self.ShellCommand = 'shell2'
        self.UpdateCommand = 'update2'
        self.ExecHelpCommand = 'exechelp2'
        self.TsHelpCommand = 'tshelp2'

BotCommands = _BotCommands()
